version: "3.9"
services:
  react:
    container_name: airline_analysis_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - ${AIRLINE_ANALYSIS_FRONTEND_PORT}:3000

  node:
    container_name: airline_analysis_backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - ${AIRLINE_ANALYSIS_BACKEND_PORT}:4201
    depends_on:
      - react
    env_file: .env
    environment:
      AIRLINE_ANALYSIS_DATABASE_CONNECTION_STRING: "${AIRLINE_ANALYSIS_DATABASE_CONNECTION_STRING}"
 
  nginx:
    depends_on:
      - react
      - node
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${AIRLINE_ANALYSIS_NGINX_PORT}:80
