version: "3.9"
services:
  react:
    volumes:
      - frontend-content:/app/frontend/build/
    container_name: airline_analysis_frontend
    build:
      context: ./frontend
    ports:
      - ${AIRLINE_ANALYSIS_FRONTEND_PORT}:3000

  node:
    volumes:
      - frontend-content:/app/backend/src/build

    container_name: airline_analysis_backend
    build:
      context: ./backend
    ports:
      - ${AIRLINE_ANALYSIS_BACKEND_PORT}:4201
    depends_on:
      - react
    environment:
      AIRLINE_ANALYSIS_BACKEND_PORT: 4201

  nginx:
    depends_on:
      - react
      - node
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${AIRLINE_ANALYSIS_NGINX_PORT}:80
